### ISSUE TITLE
дублювання

### ISSUE THREAD

**Issue by pecourses** [Alex880401/box-model#5]
https://github.com/Alex880401/box-model/blob/57e196f506f7bb8a4b000e91e6e83deb0f939126/style.css#L89-L107
- ці дві секції мають практично ідентичні стилі. В таких випадках, якщо треба буде внести в них зміни, доведеться вносити абсолютно однакові зміни в різні рядки коду. З одного боку, це вимагатиме більше часу, з іншого - більше правок - більша ймовірність виникнення помилки.
Тому для подібних випадків стараються об'єднати блоки коду, які дублюються, разом, в єдине джерело істини. Наприклад, це можна зробити так:
```css
#section-4-l,
#section-4-r {
  display: inline-block;
  box-sizing: border-box;
  width: 50%;
  height: inherit;
  padding: 0 20px 0;
  font-size: 16px;
}
#section-4-l {
  background-color: rgb(41, 126, 206);
}

#section-4-r {
  background-color: rgb(48, 46, 46);
}
```
